package update

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/s0beran0/ngx/internal/output"
)

// RepoPadrao is the repository that gets consulted. It lives here, and not in
// a flag, because pointing the update at another repository would be pointing
// it at another source of binaries -- a build decision, not a command-line
// one.
const RepoPadrao = "s0beran0/ngx"

// BaseURLPadrao is the root of the GitHub API. Overridden only in tests.
const BaseURLPadrao = "https://api.github.com"

// Names of the verification artifacts generated by goreleaser (DD2).
const (
	NomeChecksums  = "checksums.txt"
	NomeAssinatura = "checksums.txt.minisig"
)

// limiteDownload caps what we accept to read from the network into memory. An
// ngx artifact is a few dozen megabytes; with no ceiling, a hostile server
// (or a redirect to the wrong place) takes the machine down through memory
// consumption instead of failing.
const limiteDownload = 128 << 20 // 128 MiB

// Asset is an artifact attached to a release.
type Asset struct {
	Name string `json:"name"`
	URL  string `json:"browser_download_url"`
	Size int64  `json:"size"`
}

// Release is a GitHub release, in the subset of fields the update uses.
type Release struct {
	Version    string  `json:"tag_name"`
	Prerelease bool    `json:"prerelease"`
	Draft      bool    `json:"draft"`
	Assets     []Asset `json:"assets"`
}

// AssetPorNome returns the artifact with the exact name.
func (r *Release) AssetPorNome(nome string) (Asset, error) {
	for _, a := range r.Assets {
		if a.Name == nome {
			return a, nil
		}
	}
	return Asset{}, erro(CodigoAssetAusente,
		"release %s does not carry the file %q, so there is no way to verify the download; "+
			"published artifacts: %s", r.Version, nome, listaDeNomes(r.Assets))
}

// AssetDaPlataforma picks the artifact for the given system and
// architecture. The choice is made by suffix (_<so>_<arch>.<ext>) instead of
// by a name assembled from the version: the goreleaser name template can
// change without the update having to be rewritten.
func (r *Release) AssetDaPlataforma(so, arch string) (Asset, error) {
	sufixos := []string{
		fmt.Sprintf("_%s_%s.tar.gz", so, arch),
		fmt.Sprintf("_%s_%s.zip", so, arch),
	}
	for _, s := range sufixos {
		for _, a := range r.Assets {
			if strings.HasSuffix(a.Name, s) {
				return a, nil
			}
		}
	}
	return Asset{}, erro(CodigoAssetAusente,
		"release %s does not carry an artifact for %s/%s; published artifacts: %s",
		r.Version, so, arch, listaDeNomes(r.Assets))
}

func listaDeNomes(assets []Asset) string {
	if len(assets) == 0 {
		return "none"
	}
	nomes := make([]string, 0, len(assets))
	for _, a := range assets {
		nomes = append(nomes, a.Name)
	}
	return strings.Join(nomes, ", ")
}

// Cliente talks to the GitHub API.
type Cliente struct {
	HTTP    *http.Client
	BaseURL string
	Repo    string
}

// NovoCliente returns a client with the given timeout. A zero timeout means
// "no timeout of its own": the caller controls it through the context, which
// is how the CLI's global --timeout reaches here.
func NovoCliente(timeout time.Duration) *Cliente {
	return &Cliente{
		HTTP:    &http.Client{Timeout: timeout},
		BaseURL: BaseURLPadrao,
		Repo:    RepoPadrao,
	}
}

func (c *Cliente) http() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	return http.DefaultClient
}

func (c *Cliente) base() string {
	if c.BaseURL != "" {
		return strings.TrimSuffix(c.BaseURL, "/")
	}
	return BaseURLPadrao
}

func (c *Cliente) repo() string {
	if c.Repo != "" {
		return c.Repo
	}
	return RepoPadrao
}

// Latest resolves the release of the channel.
//
// Stable uses /releases/latest, which GitHub itself already filters to
// exclude prereleases and drafts. Beta uses /releases and takes the first
// non-draft entry, because the API returns them ordered by creation
// descending -- and the beta channel accepts both a prerelease and a stable,
// whichever comes first (DD1).
func (c *Cliente) Latest(ctx context.Context, canal Channel) (*Release, error) {
	if canal == ChannelBeta {
		var releases []Release
		url := fmt.Sprintf("%s/repos/%s/releases?per_page=30", c.base(), c.repo())
		if err := c.pegarJSON(ctx, url, &releases); err != nil {
			return nil, err
		}
		for i := range releases {
			if releases[i].Draft {
				continue
			}
			return normalizar(&releases[i]), nil
		}
		return nil, erro(CodigoReleaseAusente,
			"the beta channel has no published release in %s", c.repo())
	}

	var rel Release
	url := fmt.Sprintf("%s/repos/%s/releases/latest", c.base(), c.repo())
	if err := c.pegarJSON(ctx, url, &rel); err != nil {
		return nil, err
	}
	return normalizar(&rel), nil
}

// PorVersao resolves a specific version by tag. It is the downgrade path and
// the deliberate version-change path: it never happens without someone asking
// for it.
func (c *Cliente) PorVersao(ctx context.Context, versao string) (*Release, error) {
	tag := strings.TrimSpace(versao)
	if tag == "" {
		return nil, output.Usage("give the version in the vX.Y.Z format")
	}
	if !strings.HasPrefix(tag, "v") {
		tag = "v" + tag
	}
	var rel Release
	url := fmt.Sprintf("%s/repos/%s/releases/tags/%s", c.base(), c.repo(), tag)
	if err := c.pegarJSON(ctx, url, &rel); err != nil {
		return nil, err
	}
	return normalizar(&rel), nil
}

// Baixar reads a whole artifact into memory, respecting the ceiling.
func (c *Cliente) Baixar(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, erroCausa(err, CodigoRede, "invalid download url: %s", url)
	}
	req.Header.Set("Accept", "application/octet-stream")
	req.Header.Set("User-Agent", "ngx-update")

	resp, err := c.http().Do(req)
	if err != nil {
		return nil, erroCausa(err, CodigoRede,
			"could not download %s: the network failed or the time limit ran out", url)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, erro(CodigoRede,
			"the download of %s returned HTTP %d", url, resp.StatusCode)
	}

	dados, err := io.ReadAll(io.LimitReader(resp.Body, limiteDownload+1))
	if err != nil {
		return nil, erroCausa(err, CodigoRede,
			"the download of %s was interrupted before the end", url)
	}
	if int64(len(dados)) > limiteDownload {
		return nil, erro(CodigoRede,
			"the download of %s went past the limit of %d bytes and was aborted",
			url, int64(limiteDownload))
	}
	return dados, nil
}

func (c *Cliente) pegarJSON(ctx context.Context, url string, destino any) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return erroCausa(err, CodigoRede, "invalid url: %s", url)
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "ngx-update")

	resp, err := c.http().Do(req)
	if err != nil {
		return erroCausa(err, CodigoRede,
			"could not query the GitHub API at %s: the network failed or the "+
				"time limit ran out", url)
	}
	defer resp.Body.Close()

	if err := statusDaAPI(resp, url); err != nil {
		return err
	}

	corpo, err := io.ReadAll(io.LimitReader(resp.Body, limiteDownload+1))
	if err != nil {
		return erroCausa(err, CodigoRede, "the response from %s was interrupted", url)
	}
	if err := json.Unmarshal(corpo, destino); err != nil {
		return erroCausa(err, CodigoRede,
			"the response from %s is not the JSON expected from the GitHub API", url)
	}
	return nil
}

// statusDaAPI translates the HTTP status. The 403 with X-RateLimit-Remaining:
// 0 has handling of its own because it is the most likely failure in real use
// -- the GitHub API without authentication allows 60 calls per hour per IP --
// and a generic error would send the person investigating the network or the
// repository.
func statusDaAPI(resp *http.Response, url string) error {
	switch resp.StatusCode {
	case http.StatusOK:
		return nil
	case http.StatusForbidden, http.StatusTooManyRequests:
		if resp.Header.Get("X-RateLimit-Remaining") == "0" {
			return erro(CodigoRateLimit,
				"the GitHub API rate limit was reached%s. It is not a problem with "+
					"ngx nor with your network: the API without authentication allows "+
					"60 calls per hour per IP. Wait for the window to reopen or download "+
					"the new version manually from the releases page",
				quandoReabre(resp))
		}
		return erro(CodigoRede, "the GitHub API refused the query to %s with HTTP %d",
			url, resp.StatusCode)
	case http.StatusNotFound:
		// The 404 on /releases/latest has a common and far from obvious
		// cause: the endpoint EXCLUDES prereleases, so a project that has
		// only published release candidates answers 404 even though it has
		// releases. Without saying so, the reader concludes the project
		// publishes nothing.
		if strings.HasSuffix(url, "/releases/latest") {
			return erro(CodigoReleaseAusente,
				"no stable release found at %s. This endpoint ignores prereleases: "+
					"if the project has only published -rc or -beta versions, "+
					"use --channel beta (or NGX_CHANNEL=beta) to reach them", url)
		}
		return erro(CodigoReleaseAusente,
			"the GitHub API did not find %s: the requested version may not exist or "+
				"may have no published release", url)
	default:
		return erro(CodigoRede, "the GitHub API returned HTTP %d for %s",
			resp.StatusCode, url)
	}
}

func quandoReabre(resp *http.Response) string {
	reset := resp.Header.Get("X-RateLimit-Reset")
	if reset == "" {
		return ""
	}
	var epoch int64
	if _, err := fmt.Sscanf(reset, "%d", &epoch); err != nil || epoch <= 0 {
		return ""
	}
	return " (the window reopens at " + time.Unix(epoch, 0).UTC().Format(time.RFC3339) + ")"
}

// normalizar guarantees that Assets is never nil: a null list would serialize
// as null and would break whoever does .length on the output.
func normalizar(r *Release) *Release {
	if r.Assets == nil {
		r.Assets = []Asset{}
	}
	return r
}

// Latest queries the official repository with the default client. It is the
// signature Task D4 specifies; whoever needs a timeout or another endpoint
// uses Cliente directly.
func Latest(ctx context.Context, canal Channel) (*Release, error) {
	return NovoCliente(0).Latest(ctx, canal)
}
